FROM envoyproxy/envoy-dev:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get -qq update \
    && apt-get -qq install --no-install-recommends -y curl vim nano\
    && apt-get -qq autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* \
RUN curl  http://controlplane.lorenzogiorgi.com:8080/envoyconfiguration/proxyID -o envoy-configuration.yaml
RUN mv ./envoy-configuration.yaml /etc/front-envoy.yaml
RUN chmod go+r /etc/front-envoy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/front-envoy.yaml", "--microservice-cluster", "front-proxy"]
